theme: jekyll-theme-architect
show_downloads: ["true"]
github:
  zip_url: https://github.com/crypticani/himmat/releases/download/v0.2/himmat.zip
  deb_url: https://crypticani.github.io/files/himmat.deb
  tar_url: https://github.com/crypticani/himmat/releases/download/v0.2/himmat.tar.gz
